#!/bin/bash

if [ $# -lt 1 ]; then
    echo "ERROR: Too few arguments"
    exit 1
fi

TEMPLATE=~/baekjoon/src/templete.cc
TARGET=~/baekjoon/src/$1.cc
LINK=~/baekjoon/focus.cc

if [ ! -f "$TARGET" ]; then
    echo "// BOJ $1" > "$TARGET"
    cat "$TEMPLATE" >> "$TARGET"
    echo "Created file $1.cc"
fi

ln -f "$TARGET" "$LINK"

